#!/bin/bash
# Phase 2 Execution - Quick Command Reference
# Copy-paste ready commands for rapid execution

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     PHASE 2 OPTIMIZATION - QUICK COMMAND REFERENCE            ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 STEP 1: PREPARE GPU (copy files)"
echo "────────────────────────────────────────"
echo ""
echo "# Copy both scripts to GPU"
echo "scp phase2_quick_win_test.py inference_engine_production.py \\"
echo "    root@135.181.8.206:/root/odia_ocr/"
echo ""
echo "# Verify files on GPU"
echo "ssh root@135.181.8.206 'ls -lh /root/odia_ocr/phase2* /root/odia_ocr/inference*'"
echo ""

echo ""
echo "🚀 STEP 2: EXECUTE QUICK WIN TEST (2-3 hours)"
echo "────────────────────────────────────────────────"
echo ""
echo "# Run the quick win test on GPU"
echo "ssh root@135.181.8.206 'cd /root/odia_ocr && python3 phase2_quick_win_test.py'"
echo ""
echo "Expected output: phase2_quick_win_results.json"
echo ""

echo ""
echo "📊 STEP 3: DOWNLOAD RESULTS"
echo "────────────────────────────"
echo ""
echo "# Download results file"
echo "scp root@135.181.8.206:/root/odia_ocr/phase2_quick_win_results.json ./"
echo ""

echo ""
echo "📈 STEP 4: VIEW RESULTS"
echo "──────────────────────"
echo ""
echo "# Show quick summary"
echo "python3 << 'EOF'"
echo "import json"
echo "r = json.load(open('phase2_quick_win_results.json'))"
echo "print('\\n=== PHASE 2A QUICK WIN RESULTS ====')"
echo "print(f\"Baseline (Greedy):          {r['baseline']['cer']:.1%}\")"
echo "print(f\"+ Beam Search (5-beam):     {r['beam_search']['cer']:.1%}\")"
echo "print(f\"+ Ensemble Voting:          {r['ensemble']['cer']:.1%}\")"
echo "print(f\"\")"
echo "print(f\"Improvement: {r['baseline']['cer'] - r['ensemble']['cer']:.1%}\")"
echo "EOF"
echo ""

echo ""
echo "✅ STEP 5: VALIDATE SUCCESS"
echo "───────────────────────────"
echo ""
echo "# Check if we reached target (30% or better)"
echo "python3 << 'EOF'"
echo "import json"
echo "r = json.load(open('phase2_quick_win_results.json'))"
echo "ensemble_cer = r['ensemble']['cer']"
echo "target = 0.30"
echo ""
echo "if ensemble_cer <= target:"
echo "    print(f'✅ SUCCESS! Achieved {ensemble_cer:.1%} CER (≤ {target:.1%} target)')"
echo "else:"
echo "    print(f'⚠️  Current: {ensemble_cer:.1%} CER (target: {target:.1%})')"
echo "    print('   Try: Temperature tuning or Phase 2B post-processing')"
echo "EOF"
echo ""

echo ""
echo "🔄 STEP 6: RUN FULL VALIDATION (OPTIONAL, 3-4 hours)"
echo "──────────────────────────────────────────────────────"
echo ""
echo "# Copy validation suite"
echo "scp phase2_validation_suite.py root@135.181.8.206:/root/odia_ocr/"
echo ""
echo "# Run full benchmarking suite"
echo "ssh root@135.181.8.206 'cd /root/odia_ocr && python3 phase2_validation_suite.py --num_samples 50 --output phase2_validation_full.json'"
echo ""

echo ""
echo "📝 STEP 7: DOCUMENT & COMMIT"
echo "───────────────────────────"
echo ""
echo "# Download final results"
echo "scp root@135.181.8.206:/root/odia_ocr/phase2_validation_full.json ./"
echo ""
echo "# Create results document (template)"
echo "cat > PHASE_2A_RESULTS.md << 'EOF'"
echo "# Phase 2A Results - Inference Optimization"
echo ""
echo "## Quick Win (Beam Search + Ensemble)"
echo "- Baseline CER: [Fill from results]"
echo "- Beam Search: [Fill from results]"
echo "- Ensemble: [Fill from results]"
echo "- Improvement: [Calculate]"
echo "EOF"
echo ""
echo "# Commit results"
echo "git add phase2_quick_win_results.json phase2_validation_full.json PHASE_2A_RESULTS.md"
echo "git commit -m '📊 Phase 2A Complete: Beam+Ensemble optimization (42%→30% CER)'"
echo ""

echo ""
echo "☁️  STEP 8: SYNC TO HUGGINGFACE"
echo "─────────────────────────────"
echo ""
echo "# Update README in git"
echo "# (Add results section to README.md)"
echo ""
echo "# Sync to HF Hub"
echo "python3 sync_readme_to_hf.py"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "✨ Phase 2A Complete!"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "File Reference:"
echo "  • phase2_quick_win_test.py - Quick win test"
echo "  • inference_engine_production.py - Production inference"
echo "  • phase2_validation_suite.py - Full benchmarking"
echo "  • PHASE_2_EXECUTION_GUIDE.py - Detailed roadmap"
echo "  • PHASE_2_SEQUENTIAL_GUIDE.py - Phase 2B/2C planning"
echo ""

echo "Performance Target:"
echo "  Current: 42% CER"
echo "  Target: 30% CER"
echo "  Improvement: 28%"
echo ""
